[package]
name = "packet_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.33.0"
smallvec = "1.10.0"
thiserror = "1.0.38"

[dev-dependencies]
anyhow = "1.0.69"
assert_no_alloc = "1.1.2"
criterion = "0.4.0"

[[bench]]
name = "parse_benchmark"
harness = false
